plugins {
    id 'com.android.application'
}

android {
    namespace 'com.app.calculatorvault'
    compileSdk 35

    defaultConfig {
        applicationId 'com.app.calculatorvault'
        minSdk 21
        targetSdk 35
        versionCode 6
        versionName '2.2.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    signingConfigs {
        release {
            storeFile rootProject.file("signing/CalculatorVault.keystore")
            storePassword "CVaultStable2026!"
            keyAlias "calculatorvault"
            keyPassword "CVaultStable2026!"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
}
